### PR TITLE
Juliana's branch

### PR DESCRIPTION
**Pull request by julz08**
hallo, i've added my link and added some css for that link

### CODE REVIEW

**Review by Csedge-Charles — APPROVED** [review]
The color scheme with the ever-changing colors fits amazing with the white background. The grocery items' simplicity is truly breath taking

**Comment by julz08** [comment]
> The color scheme with the ever-changing colors fits amazing with the white background. The grocery items' simplicity is truly breath taking

Thank you for the kind comment young sir. 😁

**Review by MattheuJ — APPROVED** [review]
ig it works or wtv 🙄

**Comment by julz08** [comment]
> ig it works or wtv 🙄

#mad

**Comment by MattheuJ** [comment]
> > ig it works or wtv 🙄
> 
> #thisissosickandyouareawsomeandrichandcool

wow, thank you Julz08.

however you will remain BLOCKED.

Please respect my decision.

#freeme

**Comment by julz08** [comment]
> > > ig it works or wtv 🙄
> > 
> > 
> > #thisissosickandyouareawsomeandrichandcool
> 
> wow, thank you Julz08.
> 
> however you will remain BLOCKED.
> 
> Please respect my decision.
> 
> #freeme

#idgaf #didnotask

**Comment by MattheuJ** [comment]
About to resolve this conflict...

dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔

**Comment by julz08** [comment]
> About to resolve this conflict...
> 
> dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔

Me when i'm crazy and insane 🤔

**Comment by GabrielMendo** [comment]
Dont know whats happening just happy to be here 👌

**Comment by ashleymmedina** [comment]
> > About to resolve this conflict...
> > dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔
> 
> Me when i'm crazy and insane 🤔

Me when I got issues..

**Comment by GabrielMendo** [comment]
womp womp!!!

**Comment by MattheuJ** [comment]
> > > About to resolve this conflict...
> > > dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔
> > 
> > 
> > Me when i'm crazy and insane 🤔
> 
> Me when I got issues..

Don't edit my replies,

I would NEVER do something like that to you guys.

#innocent #freetheguys

**Comment by julz08** [comment]
> > > About to resolve this conflict...
> > > dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔
> > 
> > 
> > Me when i'm crazy and insane 🤔
> 
> Me when I got issues..

Thank you for being a kind supporter. Clearly some other people (@MattheuJ) have no clue what that is.

**Comment by julz08** [comment]
> > > > About to resolve this conflict...
> > > > dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔
> > > 
> > > 
> > > Me when i'm crazy and insane 🤔
> > 
> > 
> > Me when I got issues..
> 
> Don't edit my replies,
> 
> I would NEVER do something like that to you guys.
> 
> #innocent #freetheguys

I wonder who started this conflict and edited our words in the first place. #TasteYourOwnMedicine

**Comment by MattheuJ** [comment]
> > > > > About to resolve this conflict...
> > > > > dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔
> > > > 
> > > > 
> > > > Me when i'm crazy and insane 🤔
> > > 
> > > 
> > > Me when I got issues..
> > 
> > 
> > Don't edit my replies,
> > I would NEVER do something like that to you guys.
> > #innocent #freetheguys
> 
> I wonder who started this conflict and edited our words in the first place. #TasteYourOwnMedicine

#falseaccusations 

julz08 is a LIAR and a HOOLIGAN. 🤔

**Comment by MattheuJ** [comment]
Thank you to @FRLOCS for finally fixing this MESSY and CONFLICT-STARTING code.

**Comment by julz08** [comment]
> > > > > > About to resolve this conflict...
> > > > > > dont know if @ashleymmedina or @julz08 have ever done something that selfless 🤔
> > > > > 
> > > > > 
> > > > > Me when i'm crazy and insane 🤔
> > > > 
> > > > 
> > > > Me when I got issues..
> > > 
> > > 
> > > Don't edit my replies,
> > > I would NEVER do something like that to you guys.
> > > #innocent #freetheguys
> > 
> > 
> > I wonder who started this conflict and edited our words in the first place. #TasteYourOwnMedicine
> 
> #falseaccusations
> 
> julz08 is a LIAR and a HOOLIGAN. 🤔

@MattheuJ IS CRAZY AND WILL NOT OWN UP TO HIS ACTIONS. 🤔

**Comment by MattheuJ** [comment]
While we are all here,

link to the best store: https://mattheuj.github.io/groceries/index.html

@julz08 @ashleymmedina @GabrielMendo @bellaesperanzaa

**Comment by julz08** [comment]
> Thank you to @FRLOCS for finally merging this EXCITING and WORLD-CHANGING code.

thank you my code is clearly so great and revolutionary that people are still commenting on my code AFTER MERGING and after it has been closed. i am so thank for your deep adoration with my code

**Comment by GabrielMendo** [comment]
I think you guys should settle this out side and through hands or...... play smash🤛

**Comment by julz08** [comment]
> > > Thank you to @FRLOCS for finally merging this EXCITING and WORLD-CHANGING code.
> > 
> > 
> > thank you my code is clearly so great and revolutionary that people are still commenting on my code AFTER MERGING and after it has been closed. i am so thankful for your deep adoration with my code
> 
> Seeing @julz08 slow link into delusion is heart breaking...
> 
> it's like she's still here 💔

Seeing @MattheuJ  be so obsessed with my code is quite sad. I hope he will create such a splendid code some time in his lifetime if he ever can.

**Pull request merged**
