### PR TITLE
Added my link👑

### PR DESCRIPTION
**Pull request by MattheuJ**

### CODE REVIEW

**Review by Csedge-Charles — COMMENTED** [review]
genuinely the best change I have ever seen. The design is so sophisticated

**Review by julz08 — APPROVED** [review]
Do better

**Review by Csedge-Charles — APPROVED** [review]
awesome

**Comment by MattheuJ** [comment]
> Do better



> This is AMAZING!!!!!!!!
> 
> BEST I'VE EVER SEEN!!!!

Thank you, Julz08

**Comment by bellaesperanzaa** [comment]
> Do better

could use improvements 🤗

**Review by ashleymmedina — APPROVED** [review]
Honestly, not as good as mine. It could use a slower animation because it hurts my eyes (it's the fact I use glasses too). Also, interesting color choices.

**Comment by julz08** [comment]
> > This is AMAZING!!!!!!!!
> > BEST I'VE EVER SEEN!!!!
> 
> Thank you, Julz08
I did not say  that. Stop trying to edit my words. #FreeSpeech

**Comment by MattheuJ** [comment]
> > > This is AMAZING!!!!!!!!
> > > BEST I'VE EVER SEEN!!!!
> > 
> > 
> > Thank you, Julz08
> > I did not say  that. Stop trying to edit my words. #FreeSpeech

You all have been BLOCKED and reported for hate speech.

#freeme

**Comment by ashleymmedina** [comment]
> Do better

I would 100% agree!!

**Comment by Csedge-Charles** [comment]
I wanted to drop you a quick note to say how impressed I am with your webpage! It's simply fantastic. The layout is clean and modern, and the way you've organized the content is really intuitive. I especially enjoyed the sleek design. It's clear you've put a lot of effort into it, and it definitely shows. Great job!"

**Pull request merged**
